### PR TITLE
updating to Polymer 1.0

### PR DESCRIPTION
**Pull request by toddradigan**

### CODE REVIEW

**Comment by toddradigan** [comment]
I've signed the CLA

**Comment by toddradigan** [comment]
All relevant associated emails have signed the CLA as well

**Comment by addyosmani** [comment]
Thanks! Left some comments. I would test this out with Polymer 1.1.1 too when you're locking in version numbers.

**Comment by addyosmani** [comment]
friendly ping

**Comment by ebidel** [comment]
Huh! I actually need this element for a project. Had to build my own :(

**Comment by addyosmani** [comment]
Awh. Sorry! We built this a while back for some a11y walkthroughs. Once this update lands will tag a new version so folks don't have to similarly rebuild.

**Comment by addyosmani** [comment]
Merging as is and will address the review comments myself in https://github.com/PolymerLabs/star-ratings/issues/8.

**Pull request merged**
